import FifthSection from '@/components/sections/home/fifth'
import FirstSection from '@/components/sections/home/first'
import FourthSection from '@/components/sections/home/fourth'
import SecondSection from '@/components/sections/home/second'
import SixthSection from '@/components/sections/home/sixth'
import ThirdSection from '@/components/sections/home/third'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Humane</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FirstSection />
        <SecondSection />
        <ThirdSection />
        <FifthSection />
        <FourthSection />
        <SixthSection />
      </main>
    </>

  )
}
