import PostSection from '@/components/sections/blog/post'
import Head from 'next/head'

export default function Post() {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PostSection />
      </main>
    </>
  )
}
